/*
 * rele,
 *
 *
 * Copyright (C) 2016 Davide Tateo & Matteo Pirotta
 * Versione 1.0
 *
 * This file is part of rele.
 *
 * rele is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * rele is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with rele.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef INCLUDE_RELE_CORE_LOGGER_BATCHDATASETLOGGER_H_
#define INCLUDE_RELE_CORE_LOGGER_BATCHDATASETLOGGER_H_

#include <iostream>

namespace ReLe
{

/*!
 * This class is the default interface for logging a dataset generated by ReLe::BatchCore.
 * Implement this interface to add different dataset logging capabilities.
 */
template<class ActionC, class StateC>
class BatchDatasetLogger
{
public:
    /*!
     * Destructor.
     */
    virtual ~BatchDatasetLogger()
    {
    }

public:
    /*!
     * This function is called automatically from ReLe::BatchCore for logging the dataset.
     * Should be overridden.
     * \param data the dataset to be logged.
     */
    virtual void log(Dataset<ActionC, StateC>& data) = 0;
};

/*!
 * This logger simply stores the dataset into a variable, to be used later in the code
 */
template<class ActionC, class StateC>
class CollectBatchDatasetLogger : public BatchDatasetLogger<ActionC, StateC>
{
public:
    //! the logged dataset
    Dataset<ActionC, StateC> data;

public:
    /*!
     * \see BatchDatasetLogger::log
     */
    void log(Dataset<ActionC, StateC>& data) override
    {
        this->data = data;
    }
};


/*!
 * This logger writes the dataset into a file.
 */
template<class ActionC, class StateC>
class WriteBatchDatasetLogger : public BatchDatasetLogger<ActionC, StateC>
{
public:
    /*!
     * Constructor.
     * \param fileName the absolute path where the dataset will be stored
     */
    WriteBatchDatasetLogger(std::string fileName) :
        fileName(fileName)
    {
    }

    /*!
     * \see BatchDatasetLogger::log
     */
    void log(Dataset<ActionC, StateC>& data) override
    {
        std::ofstream out(fileName, std::ios_base::out);

        out << std::setprecision(OS_PRECISION);
        if(out.is_open())
            data.writeToStream(out);
        out.close();
    }

private:
    std::string fileName;
};

}

#endif /* INCLUDE_RELE_CORE_LOGGER_BATCHDATASETLOGGER_H_ */
